Document: mygame
Title: Debian mygame Manual
Author: <insert document author here>
Abstract: This manual describes what mygame is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mygame/mygame.sgml.gz

Format: postscript
Files: /usr/share/doc/mygame/mygame.ps.gz

Format: text
Files: /usr/share/doc/mygame/mygame.text.gz

Format: HTML
Index: /usr/share/doc/mygame/html/index.html
Files: /usr/share/doc/mygame/html/*.html

  
